version: '3.5'

services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: ${APP_IMG}
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: ${SERVICE_TAGS}
    working_dir: /var/www/html
    volumes:
      - ./laravel/:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  # Nginx Service
  webserver:
    container_name: webserver
    image: ${WEBSERVER_IMG}
    restart: unless-stopped
    tty: true
    ports:
      - ${EXPOSED_PORT}:80
    expose:
      - ${EXPOSED_PORT}
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - ./laravel/:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  # MySQL Service
  db:
    container_name: db
    image: ${MYSQL_IMG}
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_NAME: mysql
      SERVICE_TAGS: ${SERVICE_TAGS}
    volumes:
      - ${DB_PATH}:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

# Docker Networks
networks:
  default:
    external:
      name: ${NETWORK}
