version: '3.5'

services:

  # Adminer
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    tty: true
    ports:
      - 8090:8080
    environment:
      SERVICE_NAME: adminer

# Docker Networks
networks:
  default:
    external:
      name: ${NETWORK}
